### ISSUE TITLE
Directions - localhost test ?

### ISSUE THREAD

**Issue by nandrianakos** [Esri/quickstart-map-js#118]
This is a useful tutorial. 

You report that "Directions"- Uses OAuth and requires you to sign up for a free ArcGIS Developer Subscription to use the app". 

I have a account at ArcGIS Developer and i test "Directions" on line. It is work fine!

Can i test "Directions" LOCALHOST? My test url is: http://localhost:3624/map-quickstart/html/directions/directions.html
Must i have some setting?

Thanks!

**Comment by jgravois** [comment]
@nandrianakos absolutely.  

in order to test the sample locally, you'll need to register your own application and supply an alternate [`appId`](https://github.com/Esri/quickstart-map-js/blob/master/html/directions/directions.html#L98) (to let https://arcgis.com know that its safe to redirect signed in users to a known application).

you can find more information about authentication in browser-based applications in the article below.
https://developers.arcgis.com/authentication/browser-based-user-logins/

**Comment by nandrianakos** [comment]
Thanks you very much!!!
